---
resource_types:
- name: helm3
  type: docker-image
  source:
    repository: ehealthafrica/concourse-helm-resource

resources:
- name: myapp-helm
  type: helm
  source:
    repos:
    - name: bitnami
      url: https://charts.bitnami.com/bitnami

jobs:
- name: deploy-helm-chart
  plan:
  - put: myapp-helm
    params:
      chart: bitnami/wordpress
      override_values:
      - key: wordpressUsername
        value: admin
      - key: wordpressPassword
        value: password
